blog/urls.py
from django.urls import path

from blog import views

from .feeds import AtomSiteNewsFeed, LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("addarticle/", views.addArticle, name="addarticle"),
    path("article/<slug:post>/", views.detail, name="detail"),
    path("update/<slug:slug>", views.updateArticle, name="update"),
    path("tag/<slug:slug>/", views.articles, name="tagged"),
    path("delete/<slug:slug>", views.deleteArticle, name="delete"),
    path("", views.articles, name="articles"),
    path("like/<slug:slug>", views.LikeView, name="article_like"),
    path("add_catergory/", views.addCategory, name="add_category"),
    path("category/<slug:category_slug>", views.category, name="category"),
    path("search/", views.search_view, name="search_view"),
]

core/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(os.getenv("ADMIN_INTERNAL_URL"), admin.site.urls),
    path(
        "",
        include("blog.urls", namespace="blog"),
    ),
    path(
        "users/",
        include("users.urls", namespace="users"),
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
    path(
        "oauth/",
        include("social_django.urls", namespace="social"),
    ),
    path(
        "summernote/",
        include("django_summernote.urls"),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os

from uuid import uuid4

from django.db import models
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from blog.search import update_index
from core.settings import AUTH_USER_MODEL as User

from django_summernote.fields import SummernoteTextField

# from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager

from django.db.models.signals import post_save, post_migrate


# class CustomUser(AbstractUser):
#     user_type_data = ((1, "Admin"), (2, "Editor"), (3, "reader"))
#     user_type = models.CharField(default=3, choices=user_type_data, max_length=10)


def path_and_rename(instance, filename):
    upload_to = "article_pics"
    ext = filename.split(".")[-1]
    # get filename
    if instance.pk:
        filename = "{}.{}".format(instance.pk, ext)
    else:
        # set filename as random string
        filename = "{}.{}".format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("blog:category", args=[self.slug])

    def __str__(self):
        return self.name


class Article(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status="published")

    options = (
        ("draft", "Draft"),
        ("published", "Published"),
    )

    title = models.CharField(max_length=150)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = SummernoteTextField()
    image = models.ImageField(upload_to=path_and_rename, default="article/default.jpg")
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=options, default="draft")
    slug = models.SlugField(unique=True, max_length=100)
    tags = TaggableManager()
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    likes = models.ManyToManyField(User, blank=True, related_name="likes")
    snippet = models.CharField(max_length=255)

    def total_likes(self):
        return self.likes.count()

    class Meta:
        ordering = ["-publish"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("blog:detail", args=[self.slug])

    def get_tags(self):
        """names() is a django-taggit method, returning a ValuesListQuerySet
        (basically just an iterable) containing the name of each tag as a string
        """
        return self.tags.names()

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Article, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    body = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment {self.body} by {self.user}"


LIKE_CHOICES = (
    ("Like", "Like"),
    ("Unlike", "Unlike"),
)


@receiver(post_save, sender=Article)
def update_search_index(sender, instance, **kwargs):
    update_index(instance)


# @receiver(post_migrate)
# def create_search_index(sender, **kwargs):
#     create_index()

blog/forms.py
from django import forms

# from django.forms import widgets
from django_summernote.widgets import SummernoteInplaceWidget

from .models import Article, Category, Comment

choices = Category.objects.all().values_list("name", "name")

choice_list = []

for item in choices:
    choice_list.append(item)


class ArticleForm(forms.ModelForm):
    # content = forms.CharField(widget=SummernoteInplaceWidget())

    class Meta:
        model = Article
        fields = ["title", "author", "content", "image", "tags", "category", "snippet"]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "label": "block text-white text-sm font-bold mb-2",
                    "class": "w-full px-4 py-2 bg-gray-400 border border-gray-600 rounded focus:outline-none focus:border-blue-500",
                }
            ),
            "content": SummernoteInplaceWidget(
                attrs={
                    "class": "w-full px-4 py-2 bg-gray-400 border border-gray-600 rounded focus:outline-none focus:border-blue-500"
                }
            ),
            "category": forms.Select(
                choices=choice_list,
                attrs={
                    "class": "w-full px-4 py-2 bg-gray-400 border border-gray-600 rounded focus:outline-none focus:border-blue-500"
                },
            ),
            "author": forms.TextInput(
                attrs={
                    "class": "block text-white text-sm font-bold mb-2",
                    "value": "",
                    "id": "zayyad",
                    "type": "hidden",
                }
            ),
            "tags": forms.TextInput(
                attrs={
                    "class": "w-full px-4 py-2 bg-gray-400 border border-gray-600 rounded focus:outline-none focus:border-blue-500"
                }
            ),
            "snippet": forms.Textarea(
                attrs={
                    "class": "w-full px-4 py-2 bg-gray-400 border border-gray-600 rounded focus:outline-none focus:border-blue-500"
                }
            ),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "slug"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            "content": forms.Textarea(attrs={"placeholder": "Add a comment..."}),
        }


class PostSearchForm(forms.Form):
    q = forms.CharField()
    c = forms.ModelChoiceField(queryset=Category.objects.all().order_by("name"))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["c"].label = ""
        self.fields["c"].required = False
        self.fields["c"].label = "Category"
        self.fields["q"].label = "Search For"
        self.fields["q"].widget.attrs.update({"class": "form-control"})

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# from users.models import NewUser
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import HttpResponseRedirect, get_object_or_404, redirect, render
from django.template.defaultfilters import slugify
from taggit.models import Tag

from blog.search import search
from .models import Article, Category, Comment

from .forms import ArticleForm, CommentForm, CategoryForm


@login_required
def addCategory(request):
    form = CategoryForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        form.save_m2m()

        messages.success(request, "Category created successfully")
        return redirect("blog:articles")
    context = {
        "form": form,
    }
    return render(request, "blog/addCategory.html", context)


def articles(request, slug=None):
    articles = Article.objects.all().filter(status="published")
    paginator = Paginator(articles, 5)
    page = request.GET.get("page")
    tag = None
    if slug:
        get_object_or_404(Tag, slug=slug)
    # Article.tags.most_common()[:2]
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    context = {
        "articles": articles,
        "tag": tag,
        "page": page,
    }

    return render(request, "blog/articles.html", context)


@login_required
def LikeView(request, slug):
    article = get_object_or_404(Article, slug=slug)
    article.likes.add(request.user)
    return redirect("blog:detail", article.slug)


def about(request):
    return render(request, "blog/about.html")


@login_required
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {"articles": articles}
    return render(request, "blog/dashboard.html", context)


@login_required
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    common_tags = Article.tags.most_common()[:4]
    if form.is_valid():
        article = form.save(commit=False)
        article.slug = slugify(article.title)
        article.author = request.user
        article.save()
        form.save_m2m()

        messages.success(request, "Article created successfully")
        return redirect("blog:dashboard")
    context = {
        "common_tags": common_tags,
        "form": form,
    }
    return render(request, "blog/addarticle.html", context)


def detail(request, post):
    # article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, slug=post, status="published")
    comments = article.comments.all()
    # page = request.GET.get("page", 1)

    # paginator = Paginator(allcomments, 10)
    # try:
    #     comments = paginator.page(page)
    # except PageNotAnInteger:
    #     comments = paginator.page(1)
    # except EmptyPage:
    #     comments = paginator.page(paginator.num_pages)
    article_tags = Article.tags.values_list("id", flat=True)
    similar_posts = Article.objects.filter(tags__in=article_tags).exclude(id=article.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:3]

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = article
            comment.save()
            messages.success(request, "Your comment has been added.")
            return redirect("blog:detail", post=post)
    else:
        form = CommentForm()

    # if request.method == "POST":
    #     comment_form = CommentForm(request.POST)
    #     if comment_form.is_valid():
    #         user_comment = comment_form.save(commit=False)
    #         user_comment.post = article
    #         user_comment.save()
    #         return HttpResponseRedirect(request.path_info)
    # else:
    #     comment_form = CommentForm()

    context = {
        "comment": comments,
        "comment_form": form,
        "article": article,
        "similar_posts": similar_posts,
    }

    return render(request, "blog/detail.html", context)


@login_required
def updateArticle(request, slug):
    article = get_object_or_404(Article, slug=slug)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request, "Article has been Updated")
        return redirect("blog:dashboard")
    return render(request, "blog/update.html", {"form": form})


@login_required
def deleteArticle(request, slug):
    article = get_object_or_404(Article, slug=slug)

    article.delete()

    messages.success(request, "Article Deleted Successfully")

    return redirect("blog:dashboard")


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Article.tags.most_common()[:4]
    article = Article.objects.filter(tags=tag)
    context = {
        "tag": tag,
        "common_tags": common_tags,
        "article": article,
    }
    return render(request, "article.html", context)


def category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    article = Article.objects.filter(category=category)

    context = {"category": category, "article": article}

    return render(request, "blog/category.html", context)


def category_list(request):
    category_list = Category.objects.exclude(name="default")
    context = {
        "category_list": category_list,
    }
    return context


def search_view(request):
    query = request.GET.get("q")
    if query:
        results = search(query)
    else:
        results = []

    return render(request, "blog/search.html", {"results": results, "query": query})

templates/blog/addCategory.html
{% extends "base.html" %}

{% block title %}Create a new Category{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}

    <div class="container mx-auto mt-8">
        <div class="md:w-1/2 md:mx-auto bg-white p-8 rounded-md shadow-md">
            {% if user.is_authenticated %}
                <h3 class="text-2xl font-bold mb-4">Add Category</h3>
                <hr class="my-4">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }}
                    <div class="mt-4">
                        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600">
                            Post
                        </button>
                    </div>
                </form>
            </div>
            {% else %}
                <p class="text-red-500">You're not allowed here. Please go back to the main page.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/blog/addComment.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% load crispy_forms_tags %}
{% block content %}

<div class="card my-4 container">
  <h5 class="card-header">Add Comment:</h5>
  <h3>Add Comment</h3>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit" class="btn btn-primary">Comment</button>
  </form>
</div>
{% endblock content %}

templates/blog/addarticle.html
{% extends "base.html" %}
{% block title %}Create a new Article{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}
{% if user.is_authenticated %}

<body class="font-sans bg-gray-400 text-white">

<div class="container mx-auto my-20 p-12 bg-gray-600 rounded-lg shadow-md max-w-3/4xl">
    <div class="mx-auto">
        <h3 class="text-2xl font-semibold mb-4">Add Article</h3>
        <hr class="my-4">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <div class="mt-4">
                <button type="submit" class="bg-green-700 text-white py-2 px-4 rounded-md">Post</button>
            </div>
        </form>
    </div>
</div>
<script>
    // Assuming you want to set the user.id as the value for an input field with ID 'zayyad'
    var name = "{{ user.id }}";
    document.getElementById("zayyad").value = name;
</script>


{% else %}
You are not allowed on this page
{% endif %}
</body>

{% endblock %}

templates/blog/article_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Article</legend>
                <h2>Are you sure you want to delete this article "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/blog/articles.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  INDEX
{% endblock title %}

{% block content %}

<body class="font-sans bg-gray-800 text-white">

  <!-- Main Content -->
  <div class="container mx-auto mt-8">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <!-- Blog Posts Loop -->
          {% for post in articles  %}
          <div class="bg-gray-900 p-6 rounded-lg shadow-md">
              <img src="{{post.image.url}}" alt="{{post.title}}" class="mb-4 rounded-lg">
              <h2 class="text-xl text-white font-bold mb-2">{{post.title}}</h2>
              <p class="text-gray-500">{{post.snippet|truncatechars:50}}</p>
              <a href="{{post.get_absolute_url}}" class="text-blue-500 mt-2 inline-block">Read more</a>
              <div class="flex">
                  {% for tag in post.tags.all %}
                  <a href="{% url 'blog:tagged' tag.slug %}"
                      class="mr-1 inline-block px-2 py-1 text-sm font-semibold leading-none text-white bg-blue-500 rounded-full">#{{ tag }}</a>
                  {% endfor %}
              </div>
              <div class="flex justify-between pt-4">
                  <span class="text-white">{{post.tag}}</span>
                  <span class="text-white">{{ post.publish.date }}</span>
              </div>
              <hr>
              <div class="flex justify-between pt-4">
                  <span>{{post.total_likes}}</span>
                  <span class="text-white">{{post.author}}</span>
              </div>
          </div>
          {% endfor %}
      </div>
  </div>

</body>
  
{% endblock %}

templates/blog/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Articles{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for post in article %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ post.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9min read</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/blog/comment.html
<div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">

        <div class="mt-3">
            <strong>{{comment.name}}</strong> 
            {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
            <small class="text-muted">On {{ comment.created.date }}</small>
        </div>
        <div class="border p-2 rounded">
            <p>{{comment.body}}</p>
            <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
        
            <div id="reply-form-container-{{comment.id}}" style="display:none">
            
                <form method="post" action="{% url 'blog:reply' %}" class="mt-3">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{post.id}}">
                    <input type="hidden" name="parent" value="{{comment.id}}">
                    <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">


                    {{comment_form.as_p}}

                    <div>
                        <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        {% for comment in comment.get_comments %}
            {% include 'comment.html' with comment=comment %}
        {% endfor %}
</div>


{% extends "base.html" %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}

      <div class="container">
        <div class="row justify-content-md-center pt-5">
          <div class="col-7"><h1>{{post.title}}</h1></div>
          <div class="col-7"><p>{{post.content|safe}}</p></div>
          <div class="col-md-7">
              {% with comments.count as total_comments %}
              <h2>
              {{ total_comments }} comment{{ total_comments|pluralize }}
              </h2>
              {% endwith %}
              {% for comment in comments %}
                Comment {{ forloop.counter }} by {{ comment.name }}
                on {{ comment.publish }}
                {{ comment.content|linebreaks }}
              {% empty %}
                <p>There are no comments for this post.</p>
              {% endfor %}
                <h2>Make a new comment</h2>

              <form id="myForm" method="post">
              {{ comment_form.as_p }}
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
              </form>

          </div>
        </div>
      </div>
      <script>
      $('#myForm').trigger("reset");
      </script>

{% endblock %}

templates/blog/dashboard.html
{% extends "base.html" %}
{% load tailwind_tags %}
{% load static %}

{% tailwind_preload_css %}
{% tailwind_css %}

{% block title %}

DASHBOARD
  
{% endblock title %}

{% block content %}
<body class="font-sans bg-gray-800 text-white"></body>
  <div class="container mx-auto">
    <main class="mt-8 p-4 bg-gray-800 rounded-md shadow-md">
      <h3 class="text-3xl text-white font-bold mb-4">Control Panel</h3>
      <hr class="my-4">
      <p class="mb-4 text-white">
        Welcome, <span class="text-sm text-white font-semibold">{{ request.user.username }}</span>
      </p>
      <hr class="my-4">
      <a href="{% url 'blog:addarticle' %}" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">
        Add Article
      </a>
      <hr class="my-4">
      {% if articles %}
      <div class="overflow-x-auto">
        <table class="w-full table-auto">
          <thead>
            <tr>
              <th scope="col" class="px-6 py-3 text-white text-left">ID</th>
              <th scope="col" class="px-6 py-3 text-white text-left">Title</th>
              <th scope="col" class="px-6 py-3 text-white text-left">Author</th>
              <th scope="col" class="px-6 py-3 text-white text-left">Date</th>
              <th scope="col" class="px-6 py-3 text-white text-center">Update</th>
              <th scope="col" class="px-6 py-3 text-white text-center">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for article in articles %}
            <tr>
              <td class="px-6 text-white py-4">{{ article.id }}</td>
              <td class="px-6 text-white py-4"><a href="{% url 'blog:detail' article.slug %}" class="text-blue-500 hover:underline">{{ article.title }}</a></td>
              <td class="px-6 text-white py-4">{{ article.author.first_name }}</td>
              <td class="px-6 text-white py-4">{{ article.publish.date }}</td>
              <td class="px-6 text-white py-4 text-center"><a href="{% url 'blog:update' article.slug %}" class="w-full bg-green-700 text-white p-2 rounded-lg shadow-lg hover:bg-white-400 focus:outline-none focus:ring focus:border-white-400">Update</a></td>
              <td class="px-6 text-white py-4 text-center"><a href="{% url 'blog:delete' article.slug %}" class="w-full bg-red-600 text-white p-2 rounded-lg shadow-lg hover:bg-white-400 focus:outline-none focus:ring focus:border-white-400">Delete</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      </main>
      <div class="mt-8 p-4 bg-red-500 text-white rounded-md">
        You don't have any articles yet...
      </div>
      {% endif %}
  </div>
</body>
{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}

    <div class="font-sans bg-gray-600">

        <!-- Main Content -->
        <div class="flex container bg-gray-600 mx-auto mt-8">

            <!-- Article Section -->
            <section class="flex-1 max-w-3xl mx-auto bg-gray-600 p-8 rounded-lg shadow-md">
                <h1 class="text-3xl font-bold mb-4">{{ article.title }}</h1>
                <p class="text-gray-200">Published on {{ article.publish.date }}</p>
                <img src="{{ article.image.url }}" alt="{{ article.title }}" class="mt-4 mb-8 w-full rounded-lg">
                <p class="text-gray-100">{{ article.content|safe }}</p>
                <form action="{% url 'blog:article_like' article.slug %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" name="article_slug" value="{{ article.slug }}" class="btn btn-primary btn-sm">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-heart" viewBox="0 0 16 16">
                            <path
                                d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                        </svg>
                        {{ article.total_likes }}
                    </button>
                </form>
            </section>

            <!-- Similar Posts Section -->
            <aside class="flex-shrink-0 w-1/4 bg-gray-600 p-4 rounded-lg shadow-md">
                <h2 class="text-2xl font-bold mb-4">Similar Posts</h2>
                <ul>
                    {% for similar in similar_posts %}
                    <li><a href="{{ similar.get_absolute_url }}"
                            class="text-blue-500 hover:underline">{{ similar.snippet|truncatechars:50 }}</a></li>
                    {% endfor %}
                </ul>
            </aside>
        </div>

        <!-- Comments Section -->
        <section class="flex-1 max-w-3xl mx-auto bg-gray-600 p-8 rounded-lg shadow-md">
            <div class="mt-8">
                <form method="post" action="{{ post.get_absolute_url }}">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <button type="submit"
                        class="bg-blue-500 text-white mt-8 items-center px-4 py-2 rounded-md hover:bg-blue-700 focus:outline-none focus:ring focus:ring-blue-200 transition-all">Add
                        Comment</button>
                </form>
            </div>
        
            <div class="mt-8">
                {% if comment %}
                <h2 class="text-2xl font-semibold mb-4">Comments</h2>
                <ul>
                    {% for comments in comment %}
                    <li class="mb-4">
                        <div class="flex items-center mb-2">
                            <span class="font-semibold text-gray-800">{{ comments.user.first_name }}</span>
                            <span class="text-gray-500 ml-2">{{ comments.created_at }}</span>
                        </div>
                        <p>{{ comments.body }}</p>
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                <p class="text-gray-500">No comments yet. Be the first to comment!</p>
                {% endif %}
            </div>
        </section>
    </div>

{% endblock %}