blog/urls.py
from django.urls import path

from blog import views

from .feeds import AtomSiteNewsFeed, LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("addarticle/", views.addArticle, name="addarticle"),
    path("article/<slug:post>/", views.detail, name="detail"),
    path("update/<slug:slug>", views.updateArticle, name="update"),
    path("tag/<slug:slug>/", views.articles, name="tagged"),
    path("delete/<slug:slug>", views.deleteArticle, name="delete"),
    path("", views.articles, name="articles"),
    path("like/<slug:slug>", views.LikeView, name="article_like"),
    path("add_catergory/", views.addCategory, name="add_category"),
    path("category/<slug:category_slug>", views.category, name="category"),
    path("search/", views.search_view, name="search_view"),
]

core/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(os.getenv("ADMIN_INTERNAL_URL"), admin.site.urls),
    path(
        "",
        include("blog.urls", namespace="blog"),
    ),
    path(
        "users/",
        include("users.urls", namespace="users"),
    ),
    path(
        "__reload__/",
        include("django_browser_reload.urls"),
    ),
    path(
        "oauth/",
        include("social_django.urls", namespace="social"),
    ),
    path(
        "summernote/",
        include("django_summernote.urls"),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

# from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView

app_name = "users"


urlpatterns = [
    path("register", views.RegisterView.as_view(), name="register"),
    path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.custom_password_reset_done,
        name="password_reset_done",
    ),
    path(
        "password_reset/complete/",
        views.custom_password_reset_complete,
        name="password_reset_complete",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("login", views.MyLoginView.as_view(), name="login"),
    path("socials", views.social_login, name="socials"),
    path("logout", views.logout_view, name="logout"),
]

blog/models.py
import os

from uuid import uuid4

from django.db import models
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from blog.search import update_index
from core.settings import AUTH_USER_MODEL as User

from django_summernote.fields import SummernoteTextField

# from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager

from django.db.models.signals import post_save, post_migrate


# class CustomUser(AbstractUser):
#     user_type_data = ((1, "Admin"), (2, "Editor"), (3, "reader"))
#     user_type = models.CharField(default=3, choices=user_type_data, max_length=10)


def path_and_rename(instance, filename):
    upload_to = "article_pics"
    ext = filename.split(".")[-1]
    # get filename
    if instance.pk:
        filename = "{}.{}".format(instance.pk, ext)
    else:
        # set filename as random string
        filename = "{}.{}".format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("blog:category", args=[self.slug])

    def __str__(self):
        return self.name


class Article(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status="published")

    options = (
        ("draft", "Draft"),
        ("published", "Published"),
    )

    title = models.CharField(max_length=150)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = SummernoteTextField()
    image = models.ImageField(upload_to=path_and_rename, default="article/default.jpg")
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=options, default="draft")
    slug = models.SlugField(unique=True, max_length=100)
    tags = TaggableManager()
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    likes = models.ManyToManyField(User, blank=True, related_name="likes")
    snippet = models.CharField(max_length=255)

    def total_likes(self):
        return self.likes.count()

    class Meta:
        ordering = ["-publish"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("blog:detail", args=[self.slug])

    def get_tags(self):
        """names() is a django-taggit method, returning a ValuesListQuerySet
        (basically just an iterable) containing the name of each tag as a string
        """
        return self.tags.names()

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Article, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    body = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment {self.body} by {self.user}"


LIKE_CHOICES = (
    ("Like", "Like"),
    ("Unlike", "Unlike"),
)


@receiver(post_save, sender=Article)
def update_search_index(sender, instance, **kwargs):
    update_index(instance)


# @receiver(post_migrate)
# def create_search_index(sender, **kwargs):
#     create_index()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            }
        )
    )

    class Meta:
        model = CustomUser
        fields = ("first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)  # Call the parent class's save method
        # Generate the username based on the user's name (you can use your custom function here)
        user.username = self.generate_unique_username(self.cleaned_data["first_name"])
        user.is_active = True
        user.is_staff = False

        if commit:
            user.save()
        return user

    def generate_unique_username(self, name):
        # Convert the user's name to a lowercase username with underscores
        base_username = name.lower().replace(" ", "_")

        # Check if the base_username is unique, if not, append a number until it is
        username = base_username
        count = 1
        while CustomUser.objects.filter(first_name=username).exists():
            username = f"{base_username}{count}"
            count += 1

        return username

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        {% include "script.html" %}
    </head>
    <body class="bg-gray-600">
        {% include "navbar.html" %}
        {% block content %}
          
        {% endblock content %}
    </body>
    {% include "footer.html" %}
</html>

templates/footer.html
{% load static %}


<footer class="bg-gray-700 p-4 text-center mt-8">
    <p class="text-gray-500">&copy; 2024 Your Blog. All rights reserved.</p>
</footer>

templates/index.html
<body class="font-sans bg-gray-100">

    <!-- Navigation -->
    <nav class="bg-blue-500 p-4 text-white">
        <div class="container mx-auto">
            <a href="#" class="text-2xl font-bold">Your Blog</a>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="flex container mx-auto mt-8">

        <!-- Article Section -->
        <section class="flex-1 max-w-3xl mx-auto bg-white p-8 rounded-lg shadow-md">
            <h1 class="text-3xl font-bold mb-4">Article Title</h1>
            <p class="text-gray-600">Published on January 23, 2024</p>
            <img src="{{article.image.url}}" alt="{{article.title}}" class="mt-4 mb-8 w-full rounded-lg">
            <p class="text-gray-800">{{article.content|safe}}</p>
            <form action="{% url 'blog:article_like' article.slug %}" method="POST">
                {% csrf_token %}
                <button type="submit" name="article_slug", value="{{ article.slug }}", class="btn btn-primary btn-sm">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                  <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                </svg>
                {{ article.total_likes }}
                </button>
            </form>

        </section>

        

        <!-- Similar Posts Section -->
        <aside class="flex-shrink-0 w-1/4 bg-gray-200 p-4 rounded-lg shadow-md">
            <h2 class="text-2xl font-bold mb-4">Similar Posts</h2>
            {% for similar in similar_posts  %}
            <ul>
                <li><a href="{{similar.get_absolute_url}}" class="text-blue-500 hover:underline">{{similar.snippet|truncatechars:50}}</a></li>
                <!-- Add more links based on your data -->
            </ul>
            {% endfor %}
        </aside>
    </div>

    <!-- Comments Section -->
    <section class="container mx-auto mt-8">
        <div class="max-w-3xl mx-auto bg-white p-8 rounded-lg shadow-md">
            {% with allcomments.count as total_comments  %}
              
            <h2 class="text-2xl font-bold mb-4">{{ total_comments }} Comments{{ total_comments|pluralize }}</h2>
            {% endwith %}
            <!-- Single Comment -->
            {% load mptt_tags %}

            {% recursetree comments %}
            <div id="{{ node.id }}" class="flex items-center mb-4">
                <img src="https://via.placeholder.com/40" alt="User Avatar" class="rounded-full mr-4">
                <div>
                    <figure class="tm-comment-figure">
                        <figcaption class="tm-color-primary text-center">By {{ node.name }}</figcaption>
                    </figure>
                    <p class="text-gray-600">{{ node.body }}</p>
                </div>
                <div class="flex justify-between">
                    {% if node.level < 3 %}
                        <button onclick="myFunction({{ node.id }})" class="text-blue-500 hover:underline">REPLY</button>
                        <span class="text-blue-500">{{ "June 14, 2020" }}</span>
                    {% endif %}
                </div>
                
            </div>
            <!-- Another Comment -->
            <div class="flex items-center mb-4">
                <img src="https://via.placeholder.com/40" alt="User Avatar" class="rounded-full mr-4">
                <div>
                    <p class="text-gray-800 font-semibold">Jane Doe</p>
                    <p class="text-gray-600">Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.</p>
                </div>
            </div>
            <div class="children pl-2 md:pl-5">
                {% if not node.is_leaf_node %}
                    {{ children }}
                {% endif %}
                {% endrecursetree %}
            </div>
              <br>
        </div>
        <div id="myForm">
            <form action="#" method="post">

                <!-- Name Field -->
                <div class="mb-4">
                    <label for="name" class="block text-sm font-medium text-gray-600">Name</label>
                    <input type="text" id="id_name" name="name" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-blue-500">
                </div>
    
                <!-- Email Field -->
                <div class="mb-4">
                    <label for="email" class="block text-sm font-medium text-gray-600">Email</label>
                    <input type="email" id="id_email" name="email" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-blue-500">
                </div>
    
                <!-- Body Field -->
                <div class="mb-6">
                    <label for="body" class="block text-sm font-medium text-gray-600">Comment</label>
                    <textarea id="id_body" name="body" rows="4" class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:border-blue-500"></textarea>
                </div>
    
                <!-- Submit Button -->
                <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">Submit Comment</button>
    
            </form>
        </div>
    </section>

    <!-- Footer -->
    <footer class="bg-gray-200 p-4 text-center mt-8">
        <p class="text-gray-600">&copy; 2024 Your Blog. All rights reserved.</p>
    </footer>

</body>

<script>
    function formExit() {
      document.getElementById("newForm").remove();
    }
  
    function myFunction(id) {
      if (document.contains(document.getElementById("newForm"))) {
        document.getElementById("newForm").remove();
      }
  
      var d1 = document.getElementById(id);
      d1.insertAdjacentHTML('afterend',
        '<form id="newForm" class="form-insert py-2" method="post"> \
                  <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                  <label for="id_name">Name:</label> \
                  <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                  <select name="parent" class="d-none" id="id_parentt"> \
                  <option value="' + id + '" selected="' + id + '"></option> \
                  </select> \
                  <label for="id_email">Email:</label> \
                  <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
                  <label for="id_content">Content:</label> \
                  <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                  {% csrf_token %} \
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
                </form>');
  
      //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
    }
  
    $('#myForm').trigger("reset");
  </script>

templates/navbar.html
<header class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-2 sm:px-4 lg:divide-y lg:divide-teal-700 lg:px-8">
      <div class="relative flex h-16 justify-between">
        <div class="relative z-10 flex px-2 lg:px-0">
          <div class="flex flex-shrink-0 items-center">
            <a class="h-8 w-auto" href="{% url 'blog:articles' %}" alt="">My Blog</a>
          </div>
        </div>
        <div class="relative z-0 flex flex-1 items-center justify-center px-2 sm:absolute sm:inset-0">
          <div class="w-full sm:max-w-xs">
            <label for="search" class="sr-only">Search</label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
                </svg>
              </div>
              <form action="{% url 'blog:search_view' %}" method="get">
                <div class="relative">
                    <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                        <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
                                clip-rule="evenodd" />
                        </svg>
                    </div>
                    <input id="search" name="q"
                        class="block w-full rounded-md border-0 bg-teal-500 py-1.5 pl-10 pr-3 text-yellow-300 placeholder:text-yellow-400 focus:bg-white focus:text-gray-900 focus:ring-0 focus:placeholder:text-gray-500 sm:text-sm sm:leading-6"
                        placeholder="Search" type="search">
                </div>
            </form>
            </div>
          </div>
        </div>
        <div class="relative z-10 flex items-center lg:hidden">
          <!-- Mobile menu button -->
          <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
            <span class="absolute -inset-0.5"></span>
            <span class="sr-only">Open menu</span>
            <!--
              Icon when menu is closed.
  
              Menu open: "hidden", Menu closed: "block"
            -->
            <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            <!--
              Icon when menu is open.
  
              Menu open: "block", Menu closed: "hidden"
            -->
            <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="hidden lg:relative lg:z-10 lg:ml-4 lg:flex lg:items-center">
          <button type="button" class="relative flex-shrink-0 rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
            <span class="absolute -inset-1.5"></span>
            <span class="sr-only">View notifications</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
            </svg>
          </button>
  
          <!-- Profile dropdown -->
          <div class="relative ml-4 flex-shrink-0">
            <div>
              <button type="button" class="relative flex rounded-full bg-gray-800 text-sm text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="absolute -inset-1.5"></span>
                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="#" alt="">
              </button>
            </div>
  
<!--             
              Dropdown menu, show/hide based on menu state.
  
              Entering: "transition ease-out duration-100"
                From: "transform opacity-0 scale-95"
                To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
                From: "transform opacity-100 scale-100"
                To: "transform opacity-0 scale-95"
            -->
            <!--  -->
          </div>
        </div>
      </div>
      <nav class="hidden lg:flex lg:space-x-8 lg:py-2" aria-label="Global">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
        <a href="{% url 'blog:dashboard' %}" class="bg-gray-900 text-white inline-flex items-center rounded-md py-2 px-3 text-sm font-medium" aria-current="page">Dashboard</a>
        <a href="{% url 'blog:addarticle' %}" class="text-cyan-500 bg-yellow-400 hover:bg-cyan-500 hover:text-yellow-400 inline-flex items-center rounded-md py-2 px-3 text-sm font-medium">Add Article</a>
        <a href="{% url 'blog:post_feed' %}" class="text-cyan-500 bg-yellow-400 hover:bg-cyan-500 hover:text-yellow-400 inline-flex items-center rounded-md py-2 px-3 text-sm font-medium">Projects</a>
        <a href="{% url 'blog:add_category' %}" class="text-cyan-500 bg-yellow-400 hover:bg-cyan-500 hover:text-yellow-400 inline-flex items-center rounded-md py-2 px-3 text-sm font-medium">Add Category</a>
      </nav>
    </div>
  
    <!-- Mobile menu, show/hide based on menu state. -->
    <nav class="lg:hidden" aria-label="Global" id="mobile-menu">
      <div class="space-y-1 px-2 pb-3 pt-2">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
        <a href="{% url 'blog:dashboard' %}" class="bg-gray-900 text-white block rounded-md py-2 px-3 text-base font-medium" aria-current="page">Dashboard</a>
        <a href="{% url 'blog:addarticle' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md py-2 px-3 text-base font-medium">Add article</a>
        <a href="{% url 'blog:post_feed' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md py-2 px-3 text-base font-medium">Projects</a>
        <a href="{% url 'blog:add_category' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md py-2 px-3 text-base font-medium">Add Category</a>
        
      </div>
      <div class="border-t border-gray-700 pb-3 pt-4">
        <div class="flex items-center px-4">
          <div class="flex-shrink-0">
            <!-- <img class="h-10 w-10 rounded-full" src="{% url 'users:logout' %}" alt=""> -->
          </div>
          <div class="ml-3">
            <div class="text-base font-medium text-white">Tom Cook</div>
            <div class="text-sm font-medium text-gray-400">tom@example.com</div>
          </div>
          <button type="button" class="relative ml-auto flex-shrink-0 rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
            <span class="absolute -inset-1.5"></span>
            <span class="sr-only">View notifications</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
            </svg>
          </button>
        </div>
        <div class="mt-3 space-y-1 px-2">
          {% if user.is_authenticated %}
          <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Your Profile</a>
          <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Sign out</a>
          {% else %}
          <a href="{% url 'users:register' %}" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Register</a>
          <a href="{% url 'users:login' %}" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Login</a>   
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

templates/script.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"> </script> 
<!-- <link href= 
"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" 
          rel="stylesheet" /> 
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"> </script> 
    <script src= 
"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js">  -->